pipeline {
    agent any  //  <-- This line is essential!

    stages {
        stage('Test') {
            agent { 
                docker { image 'node:16-alpine' } 
            }
            steps {
                sh 'node --version'
            }
        }
    }
}
